apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mincepierank-beta
  name: mincepierank-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mincepierank-beta
  template:
    metadata:
      labels:
        app: mincepierank-beta
      namespace: mincepierank-beta
      name: mincepierank-beta
      # annotations:
      #   prometheus.io/scrape: 'true'
      #   prometheus.io/path: '/'
      #   prometheus.io/port: '9091'
    spec:
      containers:
        - name: mincepierank-beta
          image: ghcr.io/leemartin77/mincepierank.co.uk:beta-6e9ad8d2652d43ff70779a9e02bc3312c0eb5d21
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 8080
            - name: prometheus
              containerPort: 9091
          volumeMounts:
            - name: images-dir
              mountPath: /imgprssr
          env:
            - name: IMGPRSSR_ROOT
              value: 'http://localhost:3013'
      volumes:
        - name: images-dir
          persistentVolumeClaim:
            claimName: mincepierank-imgprssr-pvc
