apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mincepierank
  name: mincepierank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mincepierank
  template:
    metadata:
      labels:
        app: mincepierank
      namespace: mincepierank
      name: mincepierank
    spec:
      containers:
        - name: mincepierank
          image: ghcr.io/leemartin77/mincepierank.co.uk:5f2443ad2f2fbaef7ff1aa29489945b5e8a4a1db
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: development
            - name: CASSANDRA_CONTACT_POINTS
              value: cassandra:9042
            - name: CASSANDRA_USER
              valueFrom:
                secretKeyRef:
                  name: cassandra-creds
                  key: cassandrauser
                  optional: false
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-creds
                  key: cassandrapassword
                  optional: false
            - name: AUTH_SECRET
              value: some-weird-random-string
