apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mincepierank
  name: mincepierank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mincepierank
  template:
    metadata:
      labels:
        app: mincepierank
      namespace: mincepierank
      name: mincepierank
    spec:
      containers:
        - name: mincepierank
          image: ghcr.io/leemartin77/mincepierank.co.uk:0df341870921516f57d9d4e6a12cf1abf4edc4ba
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: images-dir
              mountPath: /imgprssr
          env:
            - name: AUTHENTICATION
              value: development
            - name: AUTH_TRUST_HOST
              value: 'true'
            - name: IMGPRSSR_ROOT
              value: 'http://localhost:3013'
            - name: CASSANDRA_CONTACT_POINTS
              value: cassandra:9042
            - name: CASSANDRA_USER
              valueFrom:
                secretKeyRef:
                  name: cassandra-creds
                  key: cassandrauser
                  optional: false
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-creds
                  key: cassandrapassword
                  optional: false
            - name: AUTH_SECRET
              value: super-secret-string
      volumes:
        - name: images-dir
          persistentVolumeClaim:
            claimName: mincepierank-imgprssr-pvc
