apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mincepierank
  name: mincepierank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mincepierank
  template:
    metadata:
      labels:
        app: mincepierank
      namespace: mincepierank
      name: mincepierank
      # annotations:
      #   prometheus.io/scrape: 'true'
      #   prometheus.io/path: '/'
      #   prometheus.io/port: '9091'
    spec:
      containers:
        - name: mincepierank
          image: ghcr.io/leemartin77/mincepierank.co.uk:080308ef788db3cb037a70457434eb28d3da8d4f
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 8080
            - name: prometheus
              containerPort: 9091
          volumeMounts:
            - name: images-dir
              mountPath: /imgprssr
          env:
            - name: DATABASE_URL
              value: postgres://username:password@localhost:5432/mincepierank
            - name: IMGPRSSR_ROOT
              value: "http://localhost:3013"
      volumes:
        - name: images-dir
          persistentVolumeClaim:
            claimName: mincepierank-imgprssr-pvc
