apiVersion: v1
kind: Service
metadata:
  name: mincepierank
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: mincepierank
  type: ClusterIP
