apiVersion: v1
kind: Service
metadata:
  name: mincepierank-beta
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: mincepierank-beta
  type: ClusterIP
