version: '3.8'

services:
  website:
    build:
      context: .
      target: server-builder
      dockerfile: Dockerfile
    command: go run ./cmd/website/main.go
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/postgres
    ports:
      - '8080:8080'
  postgres:
    image: postgres:13.13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword