version: "3.8"

services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres:/var/lib/postgresql
      - ./data/generic:/docker-entrypoint-initdb.d/
  imgprssr:
    image: ghcr.io/leemartin77/imgprssr:latest
    ports:
      - "3000:3000"
    volumes:
      - .localimages:/images
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  dex:
    image: ghcr.io/dexidp/dex:v2.41.1-distroless
    volumes:
      - ./configs/dex-config.yaml:/etc/dex/config.yaml:ro
    ports:
      - "5556:5556"  # gRPC API
      - "5557:5557"  # HTTP endpoint
    command: ["dex", "serve", "/etc/dex/config.yaml"]
volumes:
  postgres: 
