version: 3


dotenv: ['.env']

tasks:
  generate:
    cmds:
      - cd internal/storage && sqlc generate
      - go generate ./...
  build:
    deps:
      - generate
    cmds:
      - go build -o dist/main cmd/website/main.go
  run:
    deps:
      - generate
    cmds:
      - go run cmd/website/main.go
  watch:
    deps:
      - generate
    cmds:
      - gow run cmd/website/main.go
