version: 3

tasks:
  generate:
    cmds:
      - go generate ./...
  build:
    deps:
      - generate
    cmds:
      - go build -o dist/main cmd/website/main.go
  run:
    deps:
      - generate
    cmds:
      - go run cmd/website/main.go
