// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: maker_pie_ranking.sql

package sqlcgen

import (
	"context"
)

const getUserMakerPieRanking = `-- name: GetUserMakerPieRanking :one
SELECT mpry.year, mpry.makerid, mpry.pieid, mpry.userid, mpry.pastry, mpry.filling, mpry.topping, mpry.looks, mpry.value, mpry.notes, mpry.last_updated 
FROM maker_pie_ranking_yearly mpry
WHERE
    userid = $1::text
    AND year = $2::int
    AND makerid = $3::text
    AND pieid = $4::text
`

type GetUserMakerPieRankingParams struct {
	Userid  string
	Year    int32
	Makerid string
	Pieid   string
}

func (q *Queries) GetUserMakerPieRanking(ctx context.Context, arg GetUserMakerPieRankingParams) (MakerPieRankingYearly, error) {
	row := q.db.QueryRow(ctx, getUserMakerPieRanking,
		arg.Userid,
		arg.Year,
		arg.Makerid,
		arg.Pieid,
	)
	var i MakerPieRankingYearly
	err := row.Scan(
		&i.Year,
		&i.Makerid,
		&i.Pieid,
		&i.Userid,
		&i.Pastry,
		&i.Filling,
		&i.Topping,
		&i.Looks,
		&i.Value,
		&i.Notes,
		&i.LastUpdated,
	)
	return i, err
}
