// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateMakerPie(ctx context.Context, arg CreateMakerPieParams) (string, error)
	DeleteConfig(ctx context.Context, key string) error
	DeleteMakerPieByOid(ctx context.Context, oid string) error
	GetActiveYear(ctx context.Context) (int64, error)
	GetAllConfig(ctx context.Context) ([]GetAllConfigRow, error)
	GetAllMakerPies(ctx context.Context) ([]GetAllMakerPiesRow, error)
	GetConfig(ctx context.Context, key string) (Config, error)
	GetMakerPieByOid(ctx context.Context, oid string) (GetMakerPieByOidRow, error)
	GetMakerPieYears(ctx context.Context) ([]int32, error)
	GetUserMakerPieRanking(ctx context.Context, arg GetUserMakerPieRankingParams) (MakerPieRankingYearly, error)
	InsertConfig(ctx context.Context, arg InsertConfigParams) error
	IsAdminId(ctx context.Context, userID string) (bool, error)
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) error
	UpdateMakerPieByOid(ctx context.Context, arg UpdateMakerPieByOidParams) error
	UpsertUserMakerPieRanking(ctx context.Context, arg UpsertUserMakerPieRankingParams) error
}

var _ Querier = (*Queries)(nil)
