// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetActiveYear(ctx context.Context) (int64, error)
	GetConfig(ctx context.Context, key string) (Config, error)
	IsAdminId(ctx context.Context, userID string) (bool, error)
}

var _ Querier = (*Queries)(nil)
