// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteConfig(ctx context.Context, key string) error
	GetActiveYear(ctx context.Context) (int64, error)
	GetAllConfig(ctx context.Context) ([]GetAllConfigRow, error)
	GetConfig(ctx context.Context, key string) (Config, error)
	InsertConfig(ctx context.Context, arg InsertConfigParams) error
	IsAdminId(ctx context.Context, userID string) (bool, error)
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) error
}

var _ Querier = (*Queries)(nil)
