// Code generated by generator, DO NOT EDIT.
package types

import (
	"context"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Insert new 'MakerPieYearly' into table 'maker_pie_yearly' - duplicate ids is a no-op
func MakerPieYearlyCreate(ctx context.Context, pg *pgxpool.Pool, c MakerPieYearly) (*MakerPieYearly, error) {
	args := []interface{}{
		c.Year,
		c.MakerId,
		c.Id,
		c.DisplayName,
		c.Fresh,
		c.Labels,
		c.ImageFile,
		c.WebLink,
		c.PackCount,
		c.PackPriceInPence,
	}
	sql := "INSERT INTO maker_pie_yearly (year,makerid,id,displayname,fresh,labels,image_file,web_link,pack_count,pack_price_in_pence) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING"
	_, err := pg.Exec(ctx, sql, args...)
	if err != nil {
		return nil, err
	}
	return &c, nil
}
