import Head from "next/head";
import { InferGetServerSidePropsType } from "next";
import { getMincePieMakers } from "../system/storage";
import Link from "next/link";

export const getServerSideProps = async () => {
  const data = await getMincePieMakers();
  return {
    props: {
      makers: data.unwrapOr([]),
    },
  };
};

function Home({
  makers,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Mince Pie Rank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {makers.length > 0 && (
          <ul>
            {makers.map((mkr) => (
              <li key={mkr.id}>
                <Link href={`/brands/${mkr.id}`}>{mkr.name}</Link>
              </li>
            ))}
          </ul>
        )}
      </main>
    </>
  );
}

export default Home;
