import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { randomUUID } from "crypto";
import { InferGetServerSidePropsType } from "next";
import { getMincePieMakers, Maker } from "../system/storage";

export const getServerSideProps = async () => {
  const data = await getMincePieMakers();
  return {
    props: {
      // Probably a smarter way of doing this
      makers: data.isOk() ? data._unsafeUnwrap() : [],
    },
  };
};

function Home({
  makers,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mince Pie Rank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {makers.length > 0 && (
          <ul>
            {makers.map((mkr) => (
              <li key={mkr.id}>{mkr.name}</li>
            ))}
          </ul>
        )}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export default Home;
