apiVersion: v1
kind: Service
metadata:
  name: mincepierank
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: mincepierank
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mincepierank
  name: mincepierank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mincepierank
  template:
    metadata:
      labels:
        app: mincepierank
      namespace: mincepierank
      name: mincepierank
    spec:
      containers:
        - name: mincepierank
          image: ghcr.io/leemartin77/mincepierank.co.uk:bleed
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     cpu: 1Gi
          #     memory: 2Gi
          #   requests:
          #     cpu: 0.5Gi
          #     memory: 1Gi
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: development
            - name: CASSANDRA_CONTACT_POINTS
              value: cassandra:9042
            - name: CASSANDRA_USER
              valueFrom:
                secretKeyRef:
                  name: cassandra-creds
                  key: cassandrauser
                  optional: false
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-creds
                  key: cassandrapassword
                  optional: false
            - name: NEXTAUTH_URL
              value: http://localhost:4024
            - name: NEXTAUTH_SECRET
              value: some-weird-random-string

