apiVersion: v1
kind: Service
metadata:
  name: mincepierank-imgprssr
spec:
  ports:
    - name: http
      port: 3013
      protocol: TCP
      targetPort: 3013
  selector:
    app: mincepierank-imgprssr
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: mincepierank-imgprssr
  labels:
    app: mincepierank-imgprssr
spec:
  containers:
    - name: mincepierank-imgprssr
      image: ghcr.io/leemartin77/imgprssr:v0.2.1
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 3013
      volumeMounts:
        - name: images-dir
          mountPath: /images
      env:
        - name: IMGPRSSR_IMAGE_SOURCE
          value: /images
        - name: IMGPRSSR_PORT
          value: '3013'
  volumes:
    - name: images-dir
      persistentVolumeClaim:
        claimName: mincepierank-imgprssr-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mincepierank-imgprssr-pvc
spec:
  accessModes:
    - 'ReadWriteMany'
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
  volumeName: mincepierank-imgprssr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mincepierank-imgprssr
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: '/tmp/mpr'
