name: Publish Bleed Container

on:
  push:
    branches: ["main"]

jobs:
  publish-bleed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish the Docker image
        run: |
          export REPOSITORY="ghcr.io/leemartin77/mincepierank.co.uk"
          export VERSION="v0.0.${{ github.run_number }}"

          docker build --arch amd64 -t "$REPOSITORY:amd64" . 
          docker build --arch arm64 -t "$REPOSITORY:arm64" .

          docker manifest create "$REPOSITORY:bleed" --amend "$REPOSITORY:amd64" --amend "$REPOSITORY:arm64"
          docker manifest push "$REPOSITORY:bleed"
          docker manifest create "$REPOSITORY:$VERSION" --amend "$REPOSITORY:amd64" --amend "$REPOSITORY:arm64"
          docker manifest push "$REPOSITORY:$VERSION"
