name: Publish Bleed Container

on:
  push:
    branches: ['main']

concurrency:
  group: publish-from-main
  cancel-in-progress: true

jobs:
  test-code:
    uses: ./.github/workflows/test.yml

  publish-bleed:
    needs: test-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up emulation
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/leemartin77/mincepierank.co.uk:bleed
            ghcr.io/leemartin77/mincepierank.co.uk:${{ github.sha }}
          context: .
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-version:
    needs: publish-bleed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: leemartin77/homelab.flux
          token: ${{ secrets.HOMELAB_AUTOMATION_PAT }}
      - name: Set new version
        run: echo "${{ github.sha }}" > versions/mincepierank.txt
      - name: Commit and Push version
        run: |
          git config --global user.name 'MincePieRank Bot'
          git config --global user.email 'mincepierank@users.noreply.github.com'
          git commit -am "Automated report"
          git push
